# Generated by Django 6.0 on 2025-12-16 07:14

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('chunk_index', models.IntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['source', 'chunk_index'],
            },
        ),
    ]
